### ISSUE TITLE
better window positioning

### ISSUE THREAD

**Issue by progrium** [tractordev/apptron#57]
Currently if Window X+Y are zero, the window is positioned at (0,0) which is not only a bad default (probably not what you want) but is different on different platforms (Y=0 on Mac is the bottom for example). If Width+Height are zero, you effectively get a hidden window, which might be what you want sometimes, but not if you just forgot to set width and height. Center was added to help but is not good enough. So here is a proposal to improve window positioning:

## Make Size and Position optional

Right now if not set, their zero values are used. With the rest of this proposal, we want to know whether you want the position and/or size to be (0,0) or if you don't want them set. So make them optional by changing to nil-able pointer types (`Position`=>`*Position`, `Size`=>`*Size`). 

For consistency, MinSize and MaxSize should also be made optional this way.

This also involves updating any example code to use references to the literals used. The clientjs library should update the interface so `undefined` is an allowed value and should generally be updated with all these changes. Also make sure the HTML window option utility function of apputil is updated to reflect all these changes.

## Load/save window size and position if given a name

First, this involves adding a `Name` field to window Options. This is used for persistence of identity across app loads. Then, if Size and Position are not set and we have a `Name`, we load the window's saved size+position. This is different for different platforms. The easiest being Mac since this ability is built-in:

### Mac implementation

NSWindow just needs two things set and it will save/load the window size and position (from [here](https://stackoverflow.com/a/19739462), verified):
```
window.Get("windowController").Set("shouldCascadeWindows:", core.False) // Tell controller to not cascade its windows.
window.Set("frameAutosaveName:", name) // Specify the autosave name for the window.
```
The name used for `setFrameAutosaveName:` should be the `Identifier` from the Options to app.Run plus the window `Name`. 

### Windows+Linux implementation

I believe neither has direct API to do this like Mac (though pls confirm), so we'll store it ourselves. Use `os.UserCacheDir()` for cross-platform place to make a directory. Use the `Identifier` specified by the Options to Run under the app module to make a directory there. Use `windows.json` to load/save window position using the window Name as the key. 

We don't have to write this file with every window move/resize, but it should be written when a window is closed and before the app terminates cleanly. For any window, the key/value should be merged with whatever is already in there. Writing all window frames at once to the file without using whats in there should be avoided. If an app Identifier is not used, it defaults to `com.progrium.Apptron` or something, and so multiple apps may end up using the same file. This isn't ideal, but they should at least not clobber each other.

## Add optional InitialSize and InitialPosition to Window Options

These optional params (made optional by being a nil-able pointer type) if set would be used when the there is no saved window position and no equivalent absolute params (Size, Position, now optional). 

## Default window size and position if nothing else

If Size and InitialSize are not set and there is no saved position (or Name is not set), then the default size should be 80% of the screen size. Similar for Position and InitialPosition with no save, then the default position should be centered. 

The `Center` param can stay and is equivalent to setting Position, so it will override InitialPosition and any saved position.

**Comment by nickav** [comment]
I would almost break this up into two separate changes. In my mind, we want:
1. better defaults for size / position across all platforms
2. some kind of auto save / load feature

For 1)
I could see the API mostly not needing many tweaks here. I think the main thing is to make sure that zero/nil size gets a better default. It is a little easier to make the default size a hardcoded number rather than scale based on monitor size (because that's an extra OS call), but not that difficult. We would only use the default if size is `(0, 0)`. For hiding a window you can use `Hidden`. The second thing that seems like an issue is how Y is inverted on MacOS (not sure about linux, but I think it follows windows here with top-left being `(0, 0)`).

For 2)
There is some weirdness about this being treated as a window option when it's really more of a auto save / load feature. I wonder if exposing an explicit API for this might be a little better than putting it in options. I think the window stuff should be pretty specific to just creating / managing the windows. For example, you could accomplish this with this type of API:

```go
options := window.Options{
    Title:       "Demo window",
    Visible:     false, // hide window initially
}

w1, err := window.New(options)

platform.RestoreWindowSizeAndPosition(w1, nil, window.Size{1280, 800}) // using pointers here to indicated default position (center)

w1.Show()

```

What I like about this is it's way more explicit, so hopefully users are less surprised by it. Plus that gives some more control to the application programmer if they want it.

We could take this one step further and have the `RestoreWindowSizeAndPosition` thing be a default somehow. But either way I think it makes the most sense to live in the platform layer itself somehow in terms of keeping the window stuff more focused.

**Comment by nickav** [comment]
i think we can mark this as closed but lmk what you think @progrium
